from pathlib import Path

from core.settings import get_float, get_int, get_list, get_str

BASE_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = BASE_DIR.parent

EXPORTS_DIR = PROJECT_ROOT / "data" / "exports"
MANIFEST_EXPORT_PATH = EXPORTS_DIR / "manifest_20260521T080719Z.json"
POSTGRES_EXPORT_PATH = EXPORTS_DIR / "postgres_20260521T080719Z.json"
QDRANT_EXPORT_PATH = EXPORTS_DIR / "qdrant_20260521T080719Z.json"

QDRANT_HOST = get_str("QDRANT_HOST", "localhost")
QDRANT_PORT = get_int("QDRANT_PORT", 7002)
QDRANT_COLLECTION = get_str("QDRANT_COLLECTION", "employee_faces")
QDRANT_VECTOR_SIZE = get_int("QDRANT_VECTOR_SIZE", 512)
QDRANT_DISTANCE = get_str("QDRANT_DISTANCE", "Cosine")

POSTGRES_HOST = get_str("POSTGRES_HOST", "localhost")
POSTGRES_PORT = get_int("POSTGRES_PORT", 7001)
POSTGRES_DATABASE = get_str("POSTGRES_DATABASE", "face_db")
POSTGRES_USER = get_str("POSTGRES_USER", "face_user")
POSTGRES_PASSWORD = get_str("POSTGRES_PASSWORD", "face_password")
POSTGRES_DSN = get_str(
    "POSTGRES_DSN",
    f"host={POSTGRES_HOST} port={POSTGRES_PORT} dbname={POSTGRES_DATABASE} user={POSTGRES_USER} password={POSTGRES_PASSWORD}",
)
REDIS_URL = get_str("REDIS_URL", "redis://localhost:6379/0")
DEFAULT_AI_INTERVAL = get_float("DEFAULT_AI_INTERVAL", 0.0)
STREAM_PUBLISH_FPS = get_float("STREAM_PUBLISH_FPS", 15.0)
STREAM_JPEG_QUALITY = get_int("STREAM_JPEG_QUALITY", 65)
STREAM_FRAME_TTL_SECONDS = get_int("STREAM_FRAME_TTL_SECONDS", 10)
CAMERA_ZONE_RELOAD_INTERVAL_SECONDS = get_float("CAMERA_ZONE_RELOAD_INTERVAL_SECONDS", 5.0)
DEBUG_ANNOTATED_STREAM = get_str("DEBUG_ANNOTATED_STREAM", "false").lower() in {"1", "true", "yes", "on"}
TRACKER_TYPE = get_str("TRACKER_TYPE", "bytetrack").strip().lower()
BYTETRACK_ACTIVATION_THRESHOLD = get_float("BYTETRACK_ACTIVATION_THRESHOLD", 0.25)
BYTETRACK_LOST_TRACK_BUFFER = get_int("BYTETRACK_LOST_TRACK_BUFFER", 30)
BYTETRACK_MATCHING_THRESHOLD = get_float("BYTETRACK_MATCHING_THRESHOLD", 0.8)
BYTETRACK_MIN_CONSECUTIVE_FRAMES = get_int("BYTETRACK_MIN_CONSECUTIVE_FRAMES", 1)
TRACK_STATE_TTL_SECONDS = get_float("TRACK_STATE_TTL_SECONDS", 120.0)
RABBITMQ_URL = get_str("RABBITMQ_URL", "amqp://face_user:face_password@localhost:5672/")
EMPLOYEES_TABLE = "employees"

INSIGHTFACE_DEVICE = get_str("INSIGHTFACE_DEVICE", "cpu")
INSIGHTFACE_ROOT = get_str("INSIGHTFACE_ROOT", str(PROJECT_ROOT / "models" / "insightface"))
INSIGHTFACE_DETECTION_MODEL = get_str("INSIGHTFACE_DETECTION_MODEL", "buffalo_l")
INSIGHTFACE_RECOGNITION_MODEL = get_str("INSIGHTFACE_RECOGNITION_MODEL", "buffalo_l")
INSIGHTFACE_DET_SIZE = get_int("INSIGHTFACE_DET_SIZE", 640)
MODEL_ARTIFACTS_DIR = Path(get_str("MODEL_ARTIFACTS_DIR", str(PROJECT_ROOT / "models" / "artifacts")))
TRT_ENGINE_DIR = Path(get_str("TRT_ENGINE_DIR", str(PROJECT_ROOT / "models" / "trt")))

FACE_THRESHOLD = get_float("FACE_THRESHOLD", 0.27)

LEGACY_MIN_DETECTION_SCORE = get_float("MIN_DETECTION_SCORE", 0.85)
LEGACY_MIN_FACE_WIDTH = get_int("MIN_FACE_WIDTH", 40)
LEGACY_MIN_FACE_HEIGHT = get_int("MIN_FACE_HEIGHT", 40)

TRACK_DETECTION_SCORE = get_float("TRACK_DETECTION_SCORE", 0.55)
RECOGNITION_DETECTION_SCORE = get_float("RECOGNITION_DETECTION_SCORE", LEGACY_MIN_DETECTION_SCORE)

TRACK_MIN_FACE_SIZE = get_int("TRACK_MIN_FACE_SIZE", 40)
TRACK_MIN_FACE_WIDTH = get_int("TRACK_MIN_FACE_WIDTH", TRACK_MIN_FACE_SIZE)
TRACK_MIN_FACE_HEIGHT = get_int("TRACK_MIN_FACE_HEIGHT", TRACK_MIN_FACE_SIZE)

RECOGNITION_MIN_FACE_SIZE = get_int("RECOGNITION_MIN_FACE_SIZE", min(LEGACY_MIN_FACE_WIDTH, LEGACY_MIN_FACE_HEIGHT))
RECOGNITION_MIN_FACE_WIDTH = get_int("RECOGNITION_MIN_FACE_WIDTH", RECOGNITION_MIN_FACE_SIZE)
RECOGNITION_MIN_FACE_HEIGHT = get_int("RECOGNITION_MIN_FACE_HEIGHT", RECOGNITION_MIN_FACE_SIZE)
BEST_FACE_MIN_SIZE = get_int("BEST_FACE_MIN_SIZE", 60)

# Legacy aliases kept for old modules/config. New code should use the split
# tracker/recognition thresholds above.
MIN_DETECTION_SCORE = RECOGNITION_DETECTION_SCORE
MIN_FACE_WIDTH = RECOGNITION_MIN_FACE_WIDTH
MIN_FACE_HEIGHT = RECOGNITION_MIN_FACE_HEIGHT
TOP_K = get_int("TOP_K", 5)

UNKNOWN_STABLE_FRAMES = get_int("UNKNOWN_STABLE_FRAMES", 12)
UNKNOWN_STABLE_SECONDS = get_float("UNKNOWN_STABLE_SECONDS", 1.5)
KNOWN_STABLE_FRAMES = get_int("KNOWN_STABLE_FRAMES", 1)
RECOGNITION_VOTE_WINDOW = get_int("RECOGNITION_VOTE_WINDOW", 5)
KNOWN_MIN_VOTES = get_int("KNOWN_MIN_VOTES", 2)
FACE_QUALITY_MIN_SCORE = get_float("FACE_QUALITY_MIN_SCORE", 0.25)
FACE_QUALITY_MIN_POSE_SCORE = get_float("FACE_QUALITY_MIN_POSE_SCORE", 0.4)
UNKNOWN_REID_TTL_SECONDS = get_int("UNKNOWN_REID_TTL_SECONDS", 60)
UNKNOWN_REID_THRESHOLD = get_float("UNKNOWN_REID_THRESHOLD", 0.35)
UNKNOWN_ALERT_COOLDOWN_SECONDS = get_int("UNKNOWN_ALERT_COOLDOWN_SECONDS", 300)
STORAGE_DIR = PROJECT_ROOT / "storage"
SNAPSHOT_DIR = STORAGE_DIR / "snapshots"
EVENT_LOG_PATH = STORAGE_DIR / "logs" / "events.jsonl"

CAMERA_ZONES = {
    "door_67b": {},
    "ai_pm_1": {},
    "ai_pm_2": {},
}

WORKING_HOUR_START = get_str("WORKING_HOUR_START", "08:00")
WORKING_HOUR_END = get_str("WORKING_HOUR_END", "17:30")
RESTRICTED_ZONES = get_list("RESTRICTED_ZONES", ["restricted_area", "server_room", "warehouse"])
GATE_ZONES = get_list("GATE_ZONES", ["gate"])
UNKNOWN_GATE_WARNING_FRAMES = get_int("UNKNOWN_GATE_WARNING_FRAMES", 8)
